name: build

on:
  push:
    branches:
      - master
      - release-*
    tags:
      - v*
  
  pull_request:
    branches:
      - master
      - release-*
  
jobs:
  build:
    runs-on: "runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/tag=dotnet-ci"
    env:
      NUPKG_OUTDIR: bin/Release/nugets
    steps:
      - uses: actions/checkout@v6
        with:
          clean: true
          fetch-depth: 0
          fetch-tags: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x
          dotnet-quality: 'ga'
        env:
          DOTNET_INSTALL_DIR: ${{ runner.temp }}/dotnet
      - name: Restore dependendencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Generate Packages
        run: dotnet pack --configuration Release
      - name: Upload Packages
        uses: actions/upload-artifact@v6
        with:
          name: packages
          path: ${{ env.NUPKG_OUTDIR }}
  
  discover-unit-test-projects:
    needs: ['build']
    runs-on: "runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/tag=dotnet-ci"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - id: set-matrix
        run: |
          # Find all csproj files matching the pattern recursively
          PROJECTS=$(find test -name "Diagrid.*.Test.csproj" | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=$PROJECTS" >> $GITHUB_OUTPUT

  unit-tests:
    name: Unit Tests ${{ matrix.display-name }} / ${{ matrix.os }} - ${{ matrix.project }}
    needs: ['build', 'discover-unit-test-projects']
    runs-on: "runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/tag=dotnet-ci"
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJson(needs.discover-unit-test-projects.outputs.matrix) }}
        include:
          - dotnet-version: '8.0'
            display-name: '.NET 8.0'
            framework: 'net8.0'
            prefix: 'net8'
            install-version: '8.0.x'
          - dotnet-version: '9.0'
            display-name: '.NET 9.0'
            framework: 'net9.0'
            prefix: 'net9'
            install-version: '9.0.x'
          - dotnet-version: '10.0'
            display-name: '.NET 10.0'
            framework: 'net10.0'
            prefix: 'net10'
            install-version: '10.0.x'
    steps:
      - uses: actions/checkout@v6
      - name: Parse release version
        run: python3 ./.github/scripts/get_release_version.py
      - name: Setup ${{ matrix.display-name }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.install-version }}
          dotnet-quality: 'ga' # Prefer a GA release, but use the RC if not available
        env:
          DOTNET_INSTALL_DIR: ${{ runner.temp }}/dotnet
      - name: Run Unit Tests
        id: tests
        continue-on-error: true # proceed if tests fail to allow for the report generation in master or next step failure in PR
        run: |
          dotnet test "${{ matrix.project }}"  \
          --configuration release \
          --framework ${{ matrix.framework }} \
          --logger "trx;LogFilePrefix=${{ matrix.prefix }}" \
          --logger "GitHubActions;report-warnings=false" \
          --results-directory "${{ github.workspace }}/TestResults" \
          /p:CollectCoverage=true \
          /p:CoverletOutputFormat=opencover \
          /p:GITHUB_ACTIONS=false
        timeout-minutes: 60
      - name: Check test failure in PR
        if: github.event_name == 'pull_request' && steps.tests.outcome != 'success'
        run: exit 1
      - name: Upload test coverage
        uses: codecov/codecov-action@v1
        with:
          flags: ${{ matrix.framework }}
      - name: Parse Trx files
        uses: NasAmin/trx-parser@v0.2.0
        id: trx-parser
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository # does not work on PRs from forks
        with:
          TRX_PATH: ${{ github.workspace }}/TestResults
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ci-unit-tests-gate:
    runs-on: "runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/tag=dotnet-ci"
    needs: [ 'build', 'unit-tests' ]
    steps:
      - name: "All unit tests passed"
        run: echo "All unit tests passed"

  discover-integration-test-projects:
    needs: ['build']
    runs-on: "runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/tag=dotnet-ci"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - id: set-matrix
        run: |
          PROJECTS=$(find test -name "Diagrid.*.IntegrationTest.csproj" | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=$PROJECTS" >> $GITHUB_OUTPUT

  integration-tests:
    name: Integration Tests - ${{ matrix.project }}
    needs: ['build', 'discover-integration-test-projects']
    runs-on: "runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/tag=dotnet-ci"
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJson(needs.discover-integration-test-projects.outputs.matrix) }}
        include:
          - dotnet-version: '8.0'
            display-name: '.NET 8.0'
            framework: 'net8.0'
            prefix: 'net8'
            install-version: '8.0.x'
          - dotnet-version: '9.0'
            display-name: '.NET 9.0'
            framework: 'net9.0'
            prefix: 'net9'
            install-version: '9.0.x'
          - dotnet-version: '10.0'
            display-name: '.NET 10.0'
            framework: 'net10.0'
            prefix: 'net10'
            install-version: '10.0.x'
    steps:
      - uses: actions/checkout@v6
      - name: Parse release version
        run: python3 ./.github/scripts/get_release_version.py
      - name: Setup ${{ matrix.display-name }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.install-version }}
          dotnet-quality: 'ga' # Prefer a GA release, but use the RC if not available
        env:
          DOTNET_INSTALL_DIR: ${{ runner.temp }}/dotnet
      - name: Run Integration Tests
        id: tests
        continue-on-error: true
        run: |
          dotnet test "${{ matrix.project }}"  \
          --configuration release \
          --framework ${{ matrix.framework }} \
          --logger "trx;LogFilePrefix=${{ matrix.prefix }}" \
          --logger "GitHubActions;report-warnings=false" \
          --results-directory "${{ github.workspace }}/TestResults" \
          /p:CollectCoverage=true \
          /p:CoverletOutputFormat=opencover \
          /p:GITHUB_ACTIONS=false
        timeout-minutes: 60
      - name: Check test failure in PR
        if: github.event_name == 'pull_request' && steps.tests.outcome != 'success'
        run: exit 1
      - name: Upload test coverage
        uses: codecov/codecov-action@v1
        with:
          flags: ${{ matrix.framework }}
      - name: Parse Trx files
        uses: NasAmin/trx-parser@v0.2.0
        id: trx-parser
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        with:
          TRX_PATH: ${{ github.workspace }}/TestResults
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ci-integration-tests-gate:
    runs-on: "runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/tag=dotnet-ci"
    needs: [ 'build', 'integration-tests' ]
    steps:
      - name: "All integration tests passed"
        run: echo "All integration tests passed"

  discover:
    name: 'Discover Packages'
    needs: ['build', 'ci-unit-tests-gate', 'ci-integration-tests-gate']
    runs-on: "runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/tag=dotnet-ci"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v7
        with:
          name: packages
          path: packages
      - name: List packages
        run: ls packages/*.nupkg
      - name: Generate matrix
        id: set-matrix
        run: |
          echo "Generating package matrix..."
          files=$(ls packages/*.nupkg | jq -R -s -c '
            split("\n")[:-1]
            | map(select(
                (test("/Dapr\\.Workflow\\.Versioning\\.(Abstractions|Generators|Runtime)\\.")) | not
              ))
          ')
          echo "matrix=$files" >> $GITHUB_OUTPUT

  publish:
    permissions:
      id-token: write # Enable GitHub OIDC token issuance for this job
    name: Publish Packages
    needs: ['build', 'discover']
    if: |
      startswith(github.ref, 'refs/tags/v') &&
      !(endsWith(github.ref, '-rc') || endsWith(github.ref, '-dev') || endsWith(github.ref, '-prerelease'))
    runs-on: "runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/spot=false/tag=dotnet-publish"
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.discover.outputs.matrix) }}
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v7
        with:
          name: packages
          path: packages
      - name: NuGet logic (OIDC > temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGETORG_DIAGRID_USER }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
          dotnet-quality: 'ga'
        env:
          DOTNET_INSTALL_DIR: ${{ runner.temp }}/dotnet
      - name: Publish ${{ matrix.package }} to NuGet
        run: |
          dotnet nuget push "${{ matrix.package }}" --skip-duplicate --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
